name: Caller Workflow
on:
 push:
    branches: [ "master" ]
jobs:
  build:
    uses: ehsoni/reusable-workflow/workflows/testworkflow.yaml@main
    with:
      input1: "soni"
      input2: "anvi"
     